gesdinet_jwt_refresh_token:
  ttl: 604800 # Refresh Token TTL of one week
  user_identity_field: mail
  token_parameter_name: refreshToken
  user_provider: security.user.provider.concrete.users_in_database
  single_use: true # A new refresh token will be provided if the refresh token is consumed
