#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
  path: /login

gesdinet_jwt_refresh_token:
  path:       /refresh
  controller: gesdinet.jwtrefreshtoken::refresh
  methods: POST

app.swagger_ui:
  path: /doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
  path: /doc.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }
